[package]
name = "wkhtmltox-core"
edition.workspace = true
license.workspace = true

[dependencies]
lopdf.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
wkhtmltox-pdf-sys = { path = "../wkhtmltox-pdf-sys" }

[dev-dependencies]
lopdf.workspace = true
