[package]
name = "wkhtmltox-render-chromium"
edition.workspace = true
license.workspace = true

[dependencies]
wkhtmltox-core = { path = "../wkhtmltox-core" }
serde_json.workspace = true
tempfile.workspace = true
tungstenite.workspace = true
ureq.workspace = true
base64 = "0.22"

[dev-dependencies]
image.workspace = true
lopdf.workspace = true
