# wkhtmltox-rs — Copyright 2026 wkhtmltopdf authors. LGPL-3.0-or-later.
[package]
name = "wkhtmltoimage-cli"
version = "0.12.6"
edition.workspace = true
license.workspace = true

[[bin]]
name = "wkhtmltoimage"
path = "src/main.rs"

[dependencies]
wkhtmltox-core = { path = "../wkhtmltox-core" }
wkhtmltox-render-chromium = { path = "../wkhtmltox-render-chromium" }
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true
